kind: CronJob
apiVersion: batch/v1
metadata:
  name: minute-backup
  namespace: nginx
  labels:
    app: nginx
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: minute-backup-pod
          labels:
            app: minute-backup-pod 
        spec:
          containers:
          - name: minute-backup-container
            image: busybox
            args:
            - /bin/sh
            - -c
            - >
              echo "Starting minute backup...";
              mkdir -p /backups &&
              mkdir -p /demo-data &&
              cp -r /demo-data/* /backups/ &&
              echo Backups completed at `date` >> /backups/backup.log ;
              echo "Minute backup completed.";
            volumeMounts:
            - name: data-volume
              mountPath: /demo-data
            - name: backup-volume
              mountPath: /backups
          restartPolicy: OnFailure  
          volumes:
          - name: data-volume
            hostPath:
              path: /demo-data
              type: DirectoryOrCreate
          - name: backup-volume
            hostPath:
              path: /backups
              type: DirectoryOrCreate