kind: Job
apiVersion: batch/v1
metadata:
  name: demo-job
  namespace: nginx
  labels:
    app: nginx
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: batch-task
    spec:
      containers:
      - name: Batch-container 
        image: busybox:latest
        command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 30"]
      restartPolicy: Never