kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-pv
  # namespace: nginx
  labels:
    app: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # if deleted the PV will not be deleted
  storageClassName: local-storage # we can use cloud storage network storage or some other too 
  hostPath: 
    path: /mnt/data
    type: DirectoryOrCreate