kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pv-claim
  namespace: nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage  