# simple-project.yaml

# apiVersion: v1
# kind: Namespace
# metadata:            mere hisab se already nginx namespace bana hua hai
#   name: nginx
#   labels:

# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: nginx
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      name: hello-deployment-pod
      labels:
        app: hello
    spec:
      containers:
      - name: hello-container
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: nginx
spec:
  selector:
    app: hello
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
